### ISSUE TITLE
Responsive Layouts for Mobile

### ISSUE THREAD

**Issue by lekankoku** [oxySmith/webdocs-assignment2#3]
@oxySmith @li-btu Since you didn't submit a wireframe layout for mobile, my partner and I would have to design one for you.
In the coming days, we would share our mobile design suggestions with you.

**Comment by li-btu** [comment]
@lakeside213 @Billy007p Sorry for that. A simple one would suffice. Thanks! But please note that we will need to change a bit of our requirements because our whole design is currently a dynamic web application, we will make it static webpages, as the professor suggested during our presentation. I will update the requirements and the wireframe today.

**Comment by lekankoku** [comment]
Okay, thanks for the heads up. For the conversion of the application from a dynamic to a static web application, I believe removing the cart and shopping functionality would suffice.

**Comment by li-btu** [comment]
Yes, exactly. Please do not implement cart, shopping and payment related functionality at the moment. Thanks.

**Comment by lekankoku** [comment]
Okay

**Comment by li-btu** [comment]
I have updated the wireframes, business description, webpages list and website design diagram. Please work on the latest version of them. Let me know if there is any issue. Thanks a lot!

**Comment by lekankoku** [comment]
Everything's cool now, we would work on the mobile version of the site as time goes on
